name: Testing
on: [push, pull_request]
jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node v14
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        # Remove --no-optional after Node 16 upgrade
        run: npm ci --no-optional

      - name: Run ESLint
        run: npm run lint

  typings:
    name: TSLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node v14
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        # Remove --no-optional after Node 16 upgrade
        run: npm ci --no-optional

      - name: Run TSLint
        run: npm run lint:typings

  typescript:
    name: TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node v14
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        # Remove --no-optional after Node 16 upgrade
        run: npm ci --no-optional

      - name: Register Problem Matcher
        run: echo "##[add-matcher].github/tsc.json"

      - name: Run TypeScript compiler
        run: npm run test:typescript

  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node v14
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        # Remove --no-optional after Node 16 upgrade
        run: npm ci --no-optional

      - name: Test documentation
        run: npm run docs:test
